# Generated by Django 4.1.3 on 2022-12-03 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='orderItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.orederitem'),
        ),
    ]
