# Generated by Django 4.1.3 on 2022-12-03 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_shippingaddress_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orederitem',
            old_name='date_ordred',
            new_name='date_added',
        ),
        migrations.RemoveField(
            model_name='orederitem',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='orederitem',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='orderItem',
        ),
        migrations.AddField(
            model_name='product',
            name='digital',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orederitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='Oreder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordred', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(max_length=100, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer')),
            ],
        ),
        migrations.AddField(
            model_name='orederitem',
            name='oreder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.oreder'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='oreder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.oreder'),
        ),
    ]
